apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-apache
  labels:
    name: myapp-apache
spec:
  replicas: 2
  selector:
    name: myapp-apache
  template:
    metadata:
      labels:
        name: myapp-apache
    spec:
      containers:
        - name: myapp-apache
          image: tutorials/myapp-apache
          ports:
            - containerPort: 80
              protocol: TCP
