apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    name: mariadb
spec:
  replicas: 1
  selector:
    name: mariadb
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:10.1.13-r0
          env:
            - name: MARIADB_USER
              value: myapp
            - name: MARIADB_PASSWORD
              value: secretpassword
            - name: MARIADB_DATABASE
              value: myappdb
          ports:
            - containerPort: 3306
              name: mariadb
