apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-php
  labels:
    name: myapp-php
spec:
  replicas: 2
  selector:
    name: myapp-php
  template:
    metadata:
      labels:
        name: myapp-php
    spec:
      containers:
        - name: myapp-php
          image: tutorials/myapp-php
          env:
            - name: DATABASE_HOST
              value: mariadb
            - name: DATABASE_USER
              value: myapp
            - name: DATABASE_NAME
              value: myappdb
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: myapp-secrets
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: myapp-secrets
          secret:
            secretName: myapp-secrets
